In [1]:
import numpy as np

## creating a NumPy array

In [4]:
array=np.array([5,10,15,20,25])
array

array([ 5, 10, 15, 20, 25])

## find Shape and dimension

In [10]:
a=np.shape(array)
print(a)
b=np.ndim(array)
print(b)

(5,)
1


## create an array from 1 to 10 without manually typing

In [11]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## create 3x3 filled with 0's

In [4]:
arr=np.full((3,3),0)
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## create 2x4 filled with 1's

In [8]:
arr=np.full((2,4),1)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## Square root of each element

In [12]:
arr=np.array([10,30,25,40,55])
element=np.sqrt(arr)
print(element)

[3.16227766 5.47722558 5.         6.32455532 7.41619849]


## Add 5 to each element

In [13]:
array=np.array([2,5,7,6,9])
element=array+5
element

array([ 7, 10, 12, 11, 14])

## Multiply both arrays

In [15]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
element=a*b
element

array([ 2, 12, 30])

## First row Second column

In [16]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr[1,2])

6


## Find sum of all elements in above array

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
element=np.sum(arr)
print(element)

21


## Get all values greater than 20

In [2]:
arr = np.array([10, 15, 20, 25, 30])
print(arr[arr>20])

[25 30]


## Replace all values less than 10 with 0

In [16]:
arr = np.array([5, 12, 18, 7, 25])
arr[arr<10]=0
print(arr)

[ 0 12 18  0 25]


## Create a 3×3 array with numbers from 1 to 9

In [8]:
arr=np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
arr.ndim

2

## Get the element at 2nd row, 3rd column

In [13]:
print(arr[1,2])

6


## Entire first row Entire last column

In [17]:
print(arr[0])
print(arr[:,-1])

[1 2 3]
[3 6 9]


## Shape , Total number of elements

In [5]:
element=np.shape(arr)
print(element)
element1=np.

(5,)


## Reshaping & Creation , Create array from 1 to 12 and reshape into 3×4

In [19]:
arr=np.arange(1,13,1)
element=np.reshape(arr,(3,4))
print(element)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Convert this into 2×6 shape

In [20]:
element_1=np.reshape(arr,(2,6))
print(element_1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Create an array with values from 0 to 1 (5 values evenly spaced)

array([0])

## Find: Sum of all elements , Sum column-wise

In [9]:
a = np.array([[1, 2], 
              [3, 4]])
element_1=np.sum(a)
print(element_1)
element_2=np.sum(a,axis=0)
print(element_2)

10
[4 6]


## Multiple all element by 2

In [11]:
a = np.array([[2, 4], [6, 8]])
element=np.multiply(a,2)
print(element)

[[ 4  8]
 [12 16]]


## Find dot product

In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a,b)

np.int64(32)

## Get value less than 35

In [13]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr<35])

[10 20 30]


## Replace values greater than 25 with 100

In [33]:
arr[arr>25]=100
arr

array([ 10,  20, 100, 100, 100])

## Get values Greater than 15

In [29]:
arr = np.array([[5, 15, 25],
                [10, 20, 30]])
print(arr[arr>15])

[25 20 30]


## Convert all odd numbers to -1

In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr%2==1]=-1
arr

array([-1,  2, -1,  4, -1])

## Replace: All values > 5 → 0 Others keep same

In [24]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[arr>5]=0
print(arr)

[[1 2 3]
 [4 5 0]
 [0 0 0]]


## Add 10 to each element using broadcasting

In [2]:
a = np.array([1, 2, 3])
print(a+10)

[11 12 13]


## Add both arrays

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([10, 20, 30])
print(a+b)

[[11 22 33]
 [14 25 36]]


## Get elements at index 0, 2, and 4

In [10]:
arr = np.array([10, 20, 30, 40, 50])
fancy=arr[[0,2,4]]
fancy

array([10, 30, 50])

## Find square root of each element

In [18]:
arr = np.array([4, 9, 16, 25])
root=np.sqrt(arr)
root

array([2., 3., 4., 5.])

## Get diagonal elements

In [22]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
root=arr[[0,1,2],[0,1,2]]
root

array([1, 5, 9])

## Mean & Standard deviation

In [25]:
root1=np.mean(arr)
root2=np.std(arr)
print(root1)
print(root2)

5.0
2.581988897471611


## Create array from 1 to 9 and reshape into 3×3

In [17]:
arr=np.arange(1,10,1)
element=np.reshape(arr,(3,3))
element

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Flatten this array into 1D

In [18]:
element_1=np.

AttributeError: module 'numpy' has no attribute 'flatten'

## Transpose the array

## Stack them vertically

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr=np.vstack(a)
print(arr)

[[1]
 [2]
 [3]]


## Stack horizontally

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr=np.hstack(b)
print(arr)

[4 5 6]


## Split into 3 equal parts

In [ ]:
arr = np.array([1,2,3,4,5,6])

## Sort the array

In [13]:
arr = np.array([30, 10, 50, 20])
element=arr[np.argsort(arr)]
element

array([10, 20, 30, 50])

## Sort each row

In [9]:
arr = np.array([[3,1,2],
                [6,5,4]])
element_1=np.sort(arr,axis=1)
element_1

array([[1, 2, 3],
       [4, 5, 6]])

## Find unique values

In [19]:
arr = np.array([1,2,2,3,4,4,5])
element=np.unique(arr)
element

array([1, 2, 3, 4, 5])

## Count frequency of each value

## Find index of value 20

In [28]:
arr = np.array([5, 10, 15, 20, 25])
element=np.where(arr==20)
print(element)

(array([3]),)


## Replace numbers divisible by 2 → -1

In [31]:
arr = np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

## Find max value in each column

In [7]:
arr = np.array([[10,20,30],
                [40,50,60]])
np.max(arr,axis=0)

array([40, 50, 60])

## Normalize (divide all by max value)

In [33]:
arr = np.array([10, 20, 30, 40])
arr/np.max(arr)

array([0.25, 0.5 , 0.75, 1.  ])

## Swap first row and second row

In [23]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr[[0,1]] = arr[[1,0]]
arr

array([[4, 5, 6],
       [1, 2, 3]])

## Sort each column

In [13]:
arr = np.array([[2,5,4],
                [1,6,3]])
element=np.sort(arr,axis=0)
element

array([[1, 5, 3],
       [2, 6, 4]])

## Broadcasting subtraction

In [31]:
arr = np.array([[10,20,30],
                [40,50,60]])
arr-[5,10,15]

array([[ 5, 10, 15],
       [35, 40, 45]])

## Divisible by 5

In [24]:
arr = np.array([10, 25, 30, 45, 50])
np.where(arr%5==0,1,0)

array([1, 1, 1, 1, 1])

## Even add 5, odd same

In [29]:
arr = np.array([5, 10, 15, 20])
np.where(arr%2==0,arr+5,arr)

array([ 5, 15, 15, 25])

## Middle row & column

In [12]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
element=arr[1],arr[:,1]
element

(array([4, 5, 6]), array([2, 5, 8]))

## Create array from 1 to 25 and reshape into 5×5

In [16]:
arr=np.arange(1,26)
element=np.reshape(arr,(5,5))
element

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Get diagonal elements

In [21]:
arr=np.arange(1,26)
element=np.reshape(arr,(5,5))
root=element[[0,1,2,3,4],[0,1,2,3,4]]
print(root)

[ 1  7 13 19 25]


## Greater than 10 and less than 20

In [25]:
arr=np.arange(1,26)
element=arr[(arr>10)&(arr<20)]

## Sum of each column

In [7]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
element=np.sum(arr,axis=0)
print(element)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[55 60 65 70 75]


## Mean of each row

In [13]:
arr=np.arange(1,26).reshape(5,5)
element=np.mean(arr,axis=1)
element

array([ 3.,  8., 13., 18., 23.])

## 👉 Find position (index) of value 17

In [16]:
arr=np.arange(1,26).reshape(5,5)
print(arr)
element=np.where(arr==17)
print(element)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(array([3]), array([1]))


## ## Sorting + Reverse = 👉 Sort descending

In [23]:
arr = np.array([50, 20, 40, 10, 30])
sort=np.sort(arr)
print("Ascending order:",sort)
print("Descending order:",np.sort(arr)[::-1])

Ascending order: [10 20 30 40 50]
Descending order: [50 40 30 20 10]


## Unique + Count = 👉 Find: Unique values,Frequency

In [13]:
arr = np.array([1,1,2,2,2,3,4,4])
values,count=np.unique(arr,return_counts=True)
print(values)
print(count)

[1 2 3 4]
[2 3 1 2]


## Replace: Multiples of 10 → 0

In [20]:
arr = np.array([10, 15, 20, 25, 30])
arr[arr%10==0]=0
arr

array([ 0, 15,  0, 25,  0])

## 👉 Replace: Values >20 → -1

In [22]:
arr = np.array([[5,15,25],
                [10,20,30]])
arr[arr>20]=-1
arr

array([[ 5, 15, -1],
       [10, 20, -1]])

## 👉 Get: Corner elements → (1,3,7,9)

In [23]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr[[0,0,2,2],[0,2,0,2]]

array([1, 3, 7, 9])

## 👉 Convert: Divide all elements by 2 , Then square them

In [30]:
arr = np.array([2, 4, 6, 8, 10])
element=(arr/2)**2
print(element)

[ 1.  4.  9. 16. 25.]


## 👉 Create new array: If divisible by 3 → multiply by 10

In [33]:
arr = np.array([3, 6, 9, 12])
element=np.where(arr%3==0,arr*10,arr)
element

array([ 30,  60,  90, 120])

## Get border elements (outer layer)

In [37]:
arr = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
np.concatenate((arr[0], arr[2], arr[1:-1,0], arr[1:-1, -1]))

array([10, 20, 30, 70, 80, 90, 40, 60])

## sorting first column

In [4]:
arr = np.array([[3,200],
                [1,100],
                [2,150]])
element=arr[arr[:,0].argsort()]
element

array([[  1, 100],
       [  2, 150],
       [  3, 200]])

## (Reverse Array)

In [5]:
arr = np.array([10,20,30,40,50])
element=arr[::-1]
element

array([50, 40, 30, 20, 10])

## (Swap Values)

In [8]:
arr = np.array([1,2,3,4,5])
arr[0],arr[4]=arr[4],arr[0]
arr

array([5, 2, 3, 4, 1])

## (Count Condition) greater than 15

In [10]:
arr = np.array([12, 25, 30, 7, 18])
element=np.sum(arr>15)
element

np.int64(3)

## (Row Sum Filter 🔥) 

In [11]:
arr = np.array([[1,2,3],
                [10,20,30],
                [5,5,5]])
arr[np.sum(arr,axis=1)>15]

array([[10, 20, 30]])

## (Replace Max)

In [13]:
arr = np.array([10, 50, 30, 50, 20])
arr[arr==np.max(arr)]=0
arr

array([10,  0, 30,  0, 20])

## (Column Difference)

In [16]:
arr = np.array([[10,20],
                [30,40],
                [50,60]])
arr[:,1]-arr[:,0]

array([10, 10, 10])

## (Flatten)

In [17]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.flatten()

array([1, 2, 3, 4, 5, 6])